### ISSUE TITLE
[OpenShift Container Platform] Specify nodeSelector in dns daemon set

### ISSUE THREAD

**Issue by dariodsa** [openshift/cluster-dns-operator#199]
If the OCP cluster is distributed among many different vlans, it would be easier to run dns pods in just one part of the network. That would make network administrations a lot easier and operator more flexible.

**Comment by sairamankumar2** [comment]
Hi @dariodsa,
I also want to know how to use nodeSelector in DNS daemon set. If you have any option, could you please share.

**Comment by dariodsa** [comment]
You have two options. Put nodeSelector in namespace directly, operator won't touch it, or you can wait for pull request #209 to become accepted and official.

**Comment by sairamankumar2** [comment]
Thanks @dariodsa , The solution is working.
