### ISSUE TITLE
logging in dns.operator 

### ISSUE THREAD

**Issue by ac427** [openshift/cluster-dns-operator#287]
How to enable logging in dns.operator/default ?
updating corefile in configmap/dns-default gets overwritten by the operator.

**Comment by Miciah** [comment]
The only way right now is to turn off the operator and then edit the configmap:
```
oc patch clusterversions/version --type=json --patch='[{"op":"add","path":"/spec/overrides","value":[{"kind":"Deployment","group":"apps/v1","name":"dns-operator","namespace":"openshift-dns-operator","unmanaged":true}]}]'
oc -n openshift-dns-operator scale deployments/dns-operator --replicas=0
oc -n openshift-dns edit configmaps/dns-default
```
OpenShift 4.9 will add a simpler API to turn off the DNS operator:  https://github.com/openshift/enhancements/blob/master/enhancements/dns/managementstate.md

A future release may add an API to configure logging without turning off the operator.
