### ISSUE TITLE
Support for wildcard DNS queries

### ISSUE THREAD

**Issue by pravisankar** [openshift/cluster-dns-operator#43]
Wildcard DNS queries are currently not supported by cluster dns operator. This is not implemented by upstream CoreDNS as this is not a mandatory requirement in the [dns spec] (https://github.com/kubernetes/dns/blob/master/docs/specification.md). 
We may need to implement this functionality to support backward compatibility with OpenShift 3.x release.

**Comment by ironcladlou** [comment]
Tracking this in bz/elsewhere.
