### ISSUE TITLE
Appending /etc/hosts is triggering master reboot cycles

### ISSUE THREAD

**Issue by wking** [openshift/cluster-dns-operator#63]
Since #56, this operator has been [adding content to `/etc/hosts`][1].  But that file is managed by the machine-config daemon, and when the MCD detects the altered content, [it reboots the node][2].  The node comes back up, and tries to restore the expected pods, and presumably the whole cycle repeats again.  This makes it harder for external clients to connect to the Kubernetes and OpenShift API servers (openshift/origin#21612), and that shows up in failed aws-e2e CI runs as random, unrelated flakes.  I'm not sure what the `/etc/hosts` additions are for, but can you find another approach that accomplishes the same goal?  Or find some way to ask the MCD to append your content, instead of reaching around the MCD and touching the file directly?

CC @abhinavdahiya, @ironcladlou, @pravisankar

[1]: https://github.com/openshift/cluster-dns-operator/pull/56/files#diff-042823b431ba4ecede455c65596f6b52R103
[2]: https://github.com/openshift/machine-config-operator/issues/224#issuecomment-445443040

**Comment by wking** [comment]
Possible resolution is for the MCD to stop caring about `/etc/hosts`: openshift/machine-config-operator#225.

**Comment by Miciah** [comment]
> I'm not sure what the `/etc/hosts` additions are for, but can you find another approach that accomplishes the same goal? Or find some way to ask the MCD to append your content, instead of reaching around the MCD and touching the file directly?

We update `/etc/hosts` to add the registry's name and address so that the container runtime can resolve it.  We considered using MCD, but we did not know a way to use it to update the file without triggering a reboot.  We did not realize that MCD would trigger a reboot anyway if we modified `/etc/hosts` ourselves.

**Comment by wking** [comment]
> We update `/etc/hosts` to add the registry's name and address so that the container runtime can resolve it.

Well, with openshift/machine-config-operator#225 landed, the MCD is out of the business of touching `/etc/hosts` (it had been injecting [this][1]).  Can you take over any `/etc/hosts` management that needs to happen in this operator?  It seems like a reasonable fit for the DNS operator, but I'm not familiar enough to know.

[1]: https://github.com/openshift/machine-config-operator/pull/225/files#diff-3156eff00f539873056d5edbcd50a22fL10

**Comment by ironcladlou** [comment]
@knobunc @smarterclayton any concerns with cluster-dns-operator assuming management responsibilities for `/etc/hosts` for now? I don't know of any other components who need an interface.

**Comment by ironcladlou** [comment]
@wking want to close this one out as resolved by 
https://github.com/openshift/machine-config-operator/pull/225?

**Comment by wking** [comment]
Works for me, just so y'all know you're officially in charge of the file now ;).
