### ISSUE TITLE
Node DNS sync container takes 30-60s to shut down because it doesn't handle SIGTERM properly

### ISSUE THREAD

**Issue by smarterclayton** [openshift/cluster-dns-operator#65]
Bash processes run as pid 1 need to follow a certain set of patterns in order to avoid being unresponsive when the container runtime invokes them.

Right now, the sidecar sync container is ignoring SIGTERM and so pod deletion takes however long a single wait lasts, instead of happening near instantly.  This is frustrating and delays upgrade and can lead to extended downtime on the node for DNS.

Specifically, you need to

1. Listen for SIGTERM explicitly: https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_node_group/files/sync.yaml#L59
2. Always `sleep X & wait` instead of just `sleep X`: https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/openshift_node_group/files/sync.yaml#L83
3. If you do run sub processes, be careful to wait on the right object (some examples exist, I don't have them at hand).

**Comment by pravisankar** [comment]
Fixed by https://github.com/openshift/cluster-dns-operator/pull/68
/close
